In [53]:
import numpy as np

temp = np.array([25, 28, 31, 35, 38, 27, 33, 40])

In [54]:
temp = temp + 2
temp

array([27, 30, 33, 37, 40, 29, 35, 42])

In [55]:
f = (temp * 9/5) + 32
f

array([ 80.6,  86. ,  91.4,  98.6, 104. ,  84.2,  95. , 107.6])

In [56]:
x = temp[temp > 32]
x

array([33, 37, 40, 35, 42])

In [57]:
n = np.sum(temp > 32)
n

np.int64(5)

In [58]:

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

In [59]:
t = np.sum(steps)
t

np.int64(84200)

In [60]:
m = np.mean(steps)
m


np.float64(7016.666666666667)

In [61]:
mx = np.max(steps)
mn = np.min(steps)
mx


np.int64(9500)

In [62]:
mn

np.int64(4500)

In [63]:
d = np.sum(steps, axis=0)
d

array([26500, 27300, 30400])

In [64]:
u = np.sum(steps, axis=1)
u

array([18300, 24500, 14400, 27000])

In [65]:
p = np.argmax(steps)
p

np.int64(11)

In [66]:
ori = np.array([1, 2, 3, 4, 5, 6])

In [67]:
sub = ori[1:5]

In [68]:
sub[0] = 999

In [69]:
ori

array([  1, 999,   3,   4,   5,   6])

In [70]:
sub

array([999,   3,   4,   5])

In [71]:
cp = ori[1:5].copy()
cp[0] = 500

In [72]:
ori

array([  1, 999,   3,   4,   5,   6])

In [73]:
sub

array([999,   3,   4,   5])

In [74]:
a = np.arange(1, 13)
m = a.reshape(3, 4)


In [75]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [76]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
m[0]

array([1, 2, 3, 4])

In [78]:
m[-1]

array([ 9, 10, 11, 12])

In [79]:
m[:, 1]

array([ 2,  6, 10])

In [80]:
m[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [81]:
f = m.flatten()
r = m.ravel()

In [82]:
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [83]:
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [84]:
r[0] = 100

In [85]:
m

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [86]:
r

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [87]:
f[1] = 200

In [88]:
m

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [89]:
f

array([  1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [90]:
print( m.shape)
print( m.ndim)
print(m.size)
print( m.dtype)

(3, 4)
2
12
int64


In [91]:
x = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

In [92]:
x.shape

(4, 3)

In [93]:
x.ndim

2

In [94]:
xt = x.T
xt

array([[ 6,  5,  8,  4],
       [70, 50, 80, 30],
       [ 3,  6,  2,  8]])

In [95]:
a = xt @ x
a

array([[  141,  1430,    96],
       [ 1430, 14700,   910],
       [   96,   910,   113]])

In [96]:
ai = np.linalg.inv(a)
ai

array([[ 1.10521428, -0.09848746, -0.14581398],
       [-0.09848746,  0.00891203,  0.01190129],
       [-0.14581398,  0.01190129,  0.0368847 ]])

In [97]:
b = ai @ xt @ y
b

array([-0.15921454,  0.14083853, 10.06302242])

In [98]:
new = np.array([5, 40, 7])

In [99]:
p = new @ b
p

np.float64(75.27862544778861)