In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

print(arr + 2)

print(arr * 3)

print(arr / 2)

[10 20 30 40 50]
[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

reverse = arr[::-1]

print( arr)
print("Reversed" , reverse)

[1 2 3 6 4 5]
Reversed [5 4 6 3 2 1]


In [4]:
arr[::-1]

array([5, 4, 6, 3, 2, 1])

In [5]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

In [6]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)

most_frequent = values[np.argmax(counts)]

indices = np.where(x == most_frequent)[0]

print( most_frequent)
print("Indices:", indices)

1
Indices: [0 5 7 8 9]


In [7]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

In [8]:
print(arr[0, 1])

20


In [9]:
print(arr[2, 0])

70


In [11]:
import numpy as np

Vikrant = np.linspace(10, 100, 25)

print("Array:")
print(Vikrant)

print("Dimensions:", Vikrant.ndim)
print("Shape:", Vikrant.shape)
print("Total elements:", Vikrant.size)
print(" type:", Vikrant.dtype)
print(" bytes:", Vikrant.nbytes)

transpose = Vikrant.reshape(25, 1)


print(transpose)


print(Vikrant.T)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
 type: float64
 bytes: 200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [12]:
import numpy as np

ucs420_Vikrant = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])


print(ucs420_Vikrant)

print("Mean:", np.mean(ucs420_Vikrant))
print("Median:", np.median(ucs420_Vikrant))
print("Maximum:", np.max(ucs420_Vikrant))
print("Minimum:", np.min(ucs420_Vikrant))
print("Unique elements:", np.unique(ucs420_Vikrant))

reshaped_ucs420_Vikrant = ucs420_Vikrant.reshape(4, 3)

print("Reshaped array:")
print(reshaped_ucs420_Vikrant)

resized_ucs420_Vikrant = np.resize(ucs420_Vikrant, (2, 3))

print("Resized array:")
print(resized_ucs420_Vikrant)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
[[10 20 30]
 [40 50 60]]
